const location1 = [
    "Auto Fair",
    "Autosalon",
    "Bahama Mamas Bar",
    "Capitol",
    "Cayo Perico Island",
    "Chumash",
    "Church",
    "Del Perro Pier",
    "Del Perro Beach",
    "Diamond Resort Bar (Casino Restaurant)",
    "FIB",
    "Fire Station",
    "Hospital",
    "Hotel",
    "Lifeinvader",
    "Mirror Park",
    "Paleto Bay",
    "Postal",
    "Raton Canyon",
    "Richman",
    "Rockford Hills",
    "SAHP",
    "Sandy Shores",
    "Stadium",
    "Stock Exchange",
    "Tequi-la-la Bar",
    "Vanilla Unicorn Bar",
    "Vinewood Hills",
];

const location2 = [
    "the city",
    "the airport",
    "the beach",
    "the beach market",
    "the ghetto",
    "the post office",
    "Eclipse Towers",
    "Tinsel Towers",
    "Del Perro Heights",
    "Richards Majestic",
    "Tinkle Building",
    "3 Alta Street",
    "Celltowa Building",

];

const autoNames = [
"9F",
"9F Cabrio",
"Akuma",
"Albany Escalade",
"Alpha",
"Alpha-Z1",
"Annis 350Z",
"Annis GT-R I",
"Annis RX-7 (FD)",
"Annis RX-7 (Veilside Fortune)",
"Annis Silvia (S15)",
"Annis Skyline GT-R (R34)",
"Annis WRX 2004",
"Annis ZR-350",
"Apocalypse Deathbike",
"Apocalypse Impaler",
"Apocalypse Imperator",
"Apocalypse Issi",
"Apocalypse Slamvan",
"Ardent",
"Asbo",
"Asea",
"Asterope",
"Autarch",
"Avarus",
"BF Injection",
"BF-400",
"BMX",
"Bagger",
"Baller",
"Baller LE LWB",
"Baller SG",
"Banshee",
"Banshee 900R",
"Bati 801",
"Bati 801RR",
"Beater Emperor",
"Beater Mariachi Tornado",
"Beater Surfer",
"Beater Tornado",
"Benefactor-Benz 600SEL (W140)",
"Benefactor-Benz E420 (W210)",
"Benefactor-Benz Vito (V447)",
"Benefactor-MG C63 (W205)",
"Benefactor-MG C63 Coupe (W205)",
"Benefactor-MG G63 (G770)",
"Benefactor-MG GT",
"Benefactor-MG S63 (W222)",
"Benefactor-MG SL65 (R230)",
"Benefactor-MG VT Black Series",
"Benefactor-Maybach Pullman",
"Bestia GTS",
"Bison",
"Blade",
"Blazer",
"Blazer Lifeguard",
"Blista",
"Blista Kanjo",
"Bodhi",
"Bravado Challenger 2016",
"Bravado Charger SRT",
"Bravado Charger 1969",
"Bravado Ram 1500",
"Bravado Viper 2008",
"Brawler",
"Brioso R/A",
"Buccaneer",
"Buffalo",
"Bullet",
"Burgerfahrzeug Golf GTI Vision",
"Buzzard",
"Calico GTF",
"Caracara 4x4",
"Carbon RS",
"Carbonizzare",
"Casco",
"Cavalcade",
"Cheburek",
"Cheetah",
"Cheetah Classic",
"Chimera",
"Chino",
"Cliffhanger",
"Clique",
"Cognoscenti",
"Cognoscenti 55",
"Cognoscenti Cabrio",
"Coil Cybertruck",
"Coil Model S",
"Coil Model X",
"Coil Roadster",
"Comet",
"Comet S2",
"Comet SR",
"Contender",
"Coquette",
"Coquette Blackfin",
"Coquette D10",
"Couquette Classic",
"Cruiser",
"Cuban 800",
"Cyclone",
"Cypher",
"Daemon",
"Declasse Camaro 2020",
"Declasse Corvette C7",
"Declasse Tahoe",
"Defiler",
"Deveste Eight",
"Deviant",
"Diabolus",
"Diabolus Custom",
"Dilettante",
"Dinghy",
"Dinghy (2-Seater)",
"Dinghy (Yacht)",
"Dinka NSX 2017",
"Dinka RT-3000",
"Dodo",
"Dominator",
"Dominator ASP",
"Dominator GTT",
"Dominator GTX",
"Dominator PiBwasser",
"Double-T",
"Drift Yosemite",
"Dubsta",
"Dubsta 6x6",
"Dubsta SG",
"Dukes",
"Duster",
"ETR-1",
"Elegy RH8",
"Elegy Retro Custom",
"Ellie",
"Emperor",
"Emperor LX-570",
"Emperor RCF",
"Enduro",
"Entity XF",
"Enus Continental GT",
"Enus Cullinan",
"Enus Phantom",
"Enus Spectre",
"Esskey",
"Euros",
"Exemplar",
"F620",
"FCR 1000",
"FCR 1000 Custom",
"FMJ",
"FQ 2",
"Faction",
"Faggio",
"Felon",
"Felon GT",
"Feltzer",
"Flash GT",
"Frogger",
"Fugitive",
"Furore GT",
"Fusilade",
"Futo",
"Futo GTX",
"Future Shock Deathbike",
"Future Shock Issi",
"GB200",
"GP-1",
"GT 500",
"Gallivanter Defender",
"Gallivanter Defender Christmas Edition",
"Gallivanter Defender Halloween Edition",
"Gargoyle",
"Gauntlet",
"Gauntlet Classic",
"Gauntlet Hellfire",
"Gauntlet Redwood",
"Glendale",
"Granger",
"Grotti Italia (F458)",
"Growler",
"Hakuchou",
"Hakuchou Drag",
"Hermes",
"Hexer",
"Hotknife",
"Howard NX-25",
"Huntley S",
"Imorgon",
"Impaler",
"Infernus",
"Infernus Classic",
"Ingot",
"Innovation",
"Issi",
"Itali GTB",
"Itali GTB Custom",
"Itali GTO",
"JB 700",
"Jackal",
"Jester",
"Jester (Racecar)",
"Jester Classic",
"Jester RR",
"Jetmax",
"Journey",
"Jugular",
"Kamacho",
"Karin Land Cruiser 200",
"Karin Mark 2",
"Karin Supra A80",
"Karin Tundra 2021",
"Khamelion",
"Komoda",
"Krieger",
"Lampadati Giulia GTA",
"Landstalker",
"Lectro",
"Luxor",
"Luxor Deluxe",
"Lynx",
"Malard",
"Mamba",
"Mammatus",
"Manchez",
"Marquis",
"Massacro",
"Maverick",
"Microlight",
"Monowheel",
"Monroe",
"Moonbeam",
"Nebula Turbo",
"Nemesis",
"Neon",
"Nero",
"Nero Custom",
"Nightblade",
"Nightshade",
"Nimbus",
"Novak",
"Obey A6",
"Obey A8",
"Obey Q8",
"Obey R8",
"Obey RS6",
"Obey RS7",
"Obey S8 (D4)",
"Ocelot Eletre",
"Ocelot F-Type R",
"Ocelot Vanquish Zagto SB",
"Ocelot Victor",
"Oracle",
"Osiris",
"P-45 Nokota",
"PCJ-600",
"Panto",
"Paragon R",
"Pariah",
"Patriot",
"Patriot Stretch",
"Pegassi Huayra BC",
"Pegassi Performante (LP640)",
"Penetrator",
"Penumbra",
"Peyote Gasser",
"Pfister 811",
"Pfister 918 Spyder",
"Pfister Panamera",
"Pfister Taycan",
"Pheonix",
"Picador",
"Prairie",
"Premier",
"Previon",
"Progen 675 LT",
"RE-7B",
"Raiden",
"Rancher XL",
"Rapid GT",
"Raptor",
"Rat Bike",
"Rat-Loader",
"Rat-Truck",
"Reaper",
"Rebel",
"Rebla GTS",
"Regina",
"Remus",
"Revolter",
"Rhapsody",
"Riata",
"Rocoto",
"Ruffian",
"Ruiner",
"Rumpo",
"Ruston",
"Rusty Rebel",
"SC-1",
"Sabre Turbo",
"Sanchez",
"Sanctus",
"Sandking SWB",
"Sandking XL",
"Schafter",
"Schafter LWB",
"Schafter LWB (Armored)",
"Schafter V12",
"Schlagen GT",
"Schwarzer",
"SeaShark",
"Seminole",
"Sentinel Classic",
"Sentinel XS",
"Serrano",
"Seven-70",
"Shelby GT500",
"Shotaro",
"Slam Van",
"Slamvan Custom",
"Sovereign",
"Sparrow",
"Specter",
"Speeder",
"Squalo",
"Stafford",
"Stallion",
"Stinger",
"Stinger GT",
"Stirling GT",
"Street Blazer",
"Streiter",
"Stretch",
"Stryder",
"Sultan",
"Sultan Classic",
"Sultan RS",
"Sultan RS Classic",
"Suntrap",
"Super Diamond",
"SuperVolito Carbon",
"Surano",
"Surge",
"Swift Deluxe",
"Swinger",
"T-20",
"Tailgater",
"Tailgater S",
"Taipan",
"Tampa",
"Tempesta",
"Tezeract",
"Thrax",
"Thrust",
"Tigon",
"Torero",
"Toro",
"Toros",
"Tri-Cycles Race Bike",
"Tropic",
"Tropos Rallye",
"Truffade Chiron",
"Truffade Centodieci",
"Tulip",
"Turismo Classic",
"Turismo R",
"Tyrant",
"Tyrus",
"Ubermacht 760 (LI)",
"Ubermacht I8",
"Ubermacht M3 (E46)",
"Ubermacht M3 (G80)",
"Ubermacht M4 (G82)",
"Ubermacht M4 (GTS)",
"Ubermacht M5 (CS)",
"Ubermacht M5 (CS) Halloween Edition",
"Ubermacht M5 (E34)",
"Ubermacht M5 (E60)",
"Ubermacht M8 (F91)",
"Ubermacht X5 (E70)",
"Ubermacht X5 (G05)",
"Ubermacht X6-M (E71)",
"Ubermacht X7 (G07)",
"V-65 Molotok",
"V-STR",
"Vacca",
"Vader",
"Vagner",
"Vamos",
"Vectre",
"Velierer",
"Velum",
"Vigero",
"Vindicator",
"Virgo",
"Virgo Classic",
"Viseris",
"Visione",
"Volatus",
"Voltic",
"Voodoo",
"Voodoo Custom",
"Vortex",
"Warrener",
"Warrener HKR",
"Washington",
"Whippet Race Bike",
"Windsor",
"Windsor Drop",
"Wolfsbane",
"X80 Proto",
"XA-21",
"XLS",
"XLS (Armored)",
"Yosemite",
"Yosemite Rancher",
"Z-Type",
"Zentorno",
"Zion",
"Zion Cabrio",
"Zion Classic",
"Zombie Chopper",
"Zorrusso",
];

const otherNames = [
    "Social Club. hoodie",
    "Abibas Marquee Boost Lows shoes",
    "Abibas Pezy Boost 700 V3 Alvah shoes",
    "Abibas Pezy foam shoes",
    "Abibas Pro Bounce 2019 Lows shoes",
    "Abibas leggings",
    "Abibas pants",
    "Abibas sport pants",
    "Abibas sweatpants",
    "Air Bior pullover sweater",
    "Backpack with piggy keychain skin",
    "Bigness mask",
    "Bior pants",
    "Balenciaga Track sneakers",
    "Casual neon helmet",
    "Casual neon pants",
    "Casual neon set",
    "Casual neon shoes",
    "Casual neon torso",
    "Chain bag with spikes skin",
    "Grand backpack skin",
    "Chanel top",
    "Christmas tree mask",
    "Classic Lui Vui backpack skin",
    "Cloud backpack skin",
    "Cross backpack skin",
    "LW Crossbody Bag skin",
    "Cupids crown",
    "Daft Punk mask",
    "Gingerbread house backpack skin",
    "Glowing Bomber Set NEW Sample LW",
    "Grand RP collection T-shirt",
    "Grand RP collection hoodie",
    "Grand RP collection pants",
    "Ground Mordan 4 Retro Laser 30th shoes",
    "Happy bear shoulder bag skin",
    "Hoodie with Balaclava Cap X Yazzy",
    "Jason blue mask",
    "Kolex watch of type",
    "Kolex watch",
    "LM Playboy T-shirt with luminous print",
    "LM Playboy full set with luminous print",
    "LM Playboy jacket with luminous print",
    "LM Playboy mask with luminous print",
    "LM Playboy pants with luminous print",
    "LM Playboy sweatshirt with luminous print",
    "LUV backpack with wings skin",
    "Memo Bag Ladudu",
    "Neon Chrome handbag",
    "Gauard bag with Ladudu",
    "Lui Vi T-shirt",
    "Lui Vi desert scarf mask",
    "Lui Vi full set",
    "Lui Vi jacket",
    "Lui Vi pants",
    "Lui Vi sweatshirt",
    "Lui Vi top",
    "Wide printed football T-shirt",
    "Mikachu hoodie",
    "Mordan 1 shoes",
    "Mordan 6 shoes",
    "Muci Not Fake hoodie",
    "Muci branded flip-flops",
    "Muci hoodie",
    "Muci hoodie with snake",
    "Muci pants",
    "Muci sweatshirt",
    "Muci trousers",
    "Munk mask",
    "Neon Pants Set New Sample LW",
    "Shorts Lui Vi",
    "Leather gothic pants",
    "Capsule backpack skin",
    "LV backpack with water prints skin",
    "Snake around the body accessory",
    "Acic Gel Kayano sneakers",
    "Nik mask",
    "Niki Groundporce One new collection shoes",
    "Niki Shox shoes",
    "Niki Uptempo shoes",
    "Niki Zoom Freak 1 Multi-Color shoes",
    "Niki new collection hoodie",
    "Niki new collection pants",
    "Niki tech fleece pants",
    "Niki tech top",
    "Niki track suit pants",
    "Niki track suit top",
    "Off-White Pezy Boost shoes",
    "Off-White luminous Keezy Boost shoes",
    "Off-White sweatshirt",
    "Pans sneakers",
    "Pezy Boost shoes",
    "Philip Plein T-shirt",
    "RGB neon shoes",
    "Razer headphones",
    "SSC Kit Bag skin",
    "Branded Small backpack skin",
    "Santa Claus mask",
    "Sashmello mask",
    "Scary chicken backpack skin",
    "Skeleton cheetah plush backpack skin",
    "Social Club hoodie",
    "Ston Islan Classic Sportswear",
    "T-shirt of one-color CAP brand",
    "shirts",
    "shoes",
    "clothing",
    "TRON full set",
    "TRON helmet",
    "TRON torso",
    "TRON pants",
    "TRON shoes",
    "TV-head mask",
    "The West Pace jacket",
    "Tsum collection T-shirt",
    "UP-Green Sweatshirt",
    "Vasio G-Shock watch",
    "Volex watch of type",
    "Volex watch",
    "Wedding dress",
    "Watch Me sweater",
    "Women S Love Costume",
    "alien with neon eyes mask",
    "anime mask",
    "bandana mask",
    "bandana top",
    "baseball mask",
    "black jacket with yellow trim",
    "bomber jacket with glowing elements",
    "boxing gloves",
    "boxing helmet",
    "branded Molo T-shirt",
    "branded T-shirt",
    "branded insulated hoodie",
    "branded longsleeve",
    "bright hoodie",
    "bright trousers",
    "carnival mask",
    "chain around the body accessory",
    "chain lost treasure neon accessory",
    "clown mask",
    "collection 2022 T-shirt",
    "collection 5 top",
    "corset top",
    "cowgirl hat",
    "cropp collection T-shirt",
    "day dress",
    "deer antler accessory",
    "deer antlers with a red nose accessory",
    "demon mask",
    "denim jacket",
    "desert scarf mask",
    "desert scarf mask of type",
    "devil mask",
    "dress",
    "earphones with a heart",
    "emoji mask",
    "evil mask",
    "exotic mask",
    "faution top",
    "flying bear on the shoulder accessory",
    "fox mask",
    "fur coat without a hood",
    "gloves",
    "glowing snow glasses",
    "gorilla mask",
    "Glowing face scarf mask",
    "half-glowing pants",
    "haliky T-shirt",
    "haliky hoodie",
    "handkerchief mask",
    "hearts Pride glasses",
    "insulated personal pants",
    "jacket with T-shirt",
    "jacket with luminous trim",
    "jeans",
    "jumpsuit",
    "kitsune mask",
    "long brand T-shirt",
    "low dress",
    "luminous Fendi pants",
    "luminous Grand RP trousers",
    "luminous Keezy Boost shoes",
    "luminous T-shirt",
    "luminous T-shirt of type",
    "luminous dress",
    "luminous head bag mask",
    "luminous jacket with turquoise trim",
    "luminous shoes",
    "luminous trousers",
    "luminous trousers of type",
    "luminous stones",
    "a luminous stone",
    "mix collection T-shirt",
    "monkey boss mask",
    "navel piercing accessory",
    "neck scarf accessory",
    "neon pants",
    "neon shoes",
    "new fashionable joggers",
    "owl mask",
    "panama hat",
    "penguin mask",
    "pig mask",
    "pixel glasses",
    "Grand Chain",
    " Satanic Wings",
    "pullover with long sleeve",
    "purge mask",
    "rabbit ears",
    "raccoon mask",
    "raptor mask",
    "rare luminous shoes",
    "raven mask",
    "red sneakers",
    "red stocking mask",
    "reindeer mask",
    "robot human mask",
    "robot mask",
    "rooster mask",
    "samurai mask",
    "scary turtleneck T-shirt",
    "shamanic mask",
    "shiny deer antler headband accessory",
    "short pullover",
    "Saruko neon mask",
    "skeleton king mask",
    "skirt with tights",
    "snowboarders mask",
    "snowflake glasses",
    "snowman mask",
    "sports mask",
    "stealthy mask",
    "stylish suit",
    "summer bra",
    "summer collection T-shirt",
    "summer voyage shorts",
    "tall boots",
    "tied scarf mask",
    "tight mask",
    "toothy mask",
    "top 2 outerwear",
    "top with chains",
    "trending shark head hat",
    "trendy jacket",
    "vintage Abibas Olympic Jerseys",
    "winter collection dress",
    "wristband accessory",
    "Air Bior pullover sweater",
    "black jacket with yellow trim",
    "bomber jacket with glowing elements",
    "branded insulated hoodie",
    "branded longsleeve",
    "branded T-shirt",
    "bright hoodie",
    "branded Molo T-shirt",
    "Casual neon set",
    "Casual neon torso",
    "Chanel top",
    "collection 2022 T-shirt",
    "cropp collection T-shirt",
    "denim jacket",
    "fur coat without a hood",
    "Grand RP collection hoodie",
    "Grand RP collection T-shirt",
    "haliky hoodie",
    "haliky T-shirt",
    "jacket with luminous trim",
    "jacket with T-shirt",
    "Lui Vi jacket",
    "Lui Vi sweatshirt",
    "Lui Vi full set",
    "Lui Vi T-shirt",
    "LM Playboy sweatshirt with luminous print",
    "Lui Vi top",
    "Mikachu hoodie",
    "mix collection T-shirt",
    "Muci hoodie",
    "Muci hoodie with snake",
    "Muci Not Fake hoodie",
    "Muci sweatshirt",
    "Niki new collection hoodie",
    "Niki tech top",
    "Niki track suit top",
    "Off-White sweatshirt",
    "Philip Plein T-shirt",
    "scary turtleneck T-shirt",
    "Social Club hoodie",
    "summer collection T-shirt",
    "The West Pace jacket",
    "trendy jacket",
    "TRON full Set",
    "TRON torso",
    "Tsum collection T-shirt",
    "vintage Abibas Olympic Jerseys",
    "luminous jacket with turquoise trim",
    "luminous T-shirt",
    "UP-Green Sweatshirt",
    "bandana top",
    "faution top",
    "collection 5 top",
    "corset top",
    "day dress",
    "dress",
    "jumpsuit",
    "long brand T-shirt",
    "low dress",
    "pullover with long sleeve",
    "short pullover",
    "stylish suit",
    "summer bra",
    "top 2 outerwear",
    "top with chains",
    "Watch Me sweater",
    "winter collection dress",
    "Abibas pants",
    "Abibas sport pants",
    "Abibas sweatpants",
    "bright trousers",
    "Bior pants",
    "Grand RP collection pants",
    "Muci pants",
    "Muci trousers",
    "half-glowing pants",
    "insulated personal pants",
    "Lui Vi pants",
    "luminous Fendi pants",
    "luminous Grand RP trousers",
    "LM Playboy pants with luminous print",
    "luminous trousers",
    "new fashionable joggers",
    "Niki new collection pants",
    "Niki tech fleece pants",
    "Niki track suit pants",
    "summer voyage shorts",
    "neon pants",
    "Abibas leggings",
    "Abibas pants",
    "jeans",
    "skirt with tights",
    "Muci shorts",
    "Abibas Marquee Boost Lows shoes",
    "Abibas Pro Bounce 2019 Lows shoes",
    "Abibas Pezy Boost 700 V3 Alvah shoes",
    "Abibas Pezy foam shoes",
    "Ground Mordan 4 Retro Laser 30th shoes",
    "Muci branded flip-flops",
    "Mordan 1 shoes",
    "Mordan 6 shoes",
    "luminous shoes",
    "Off-White luminous Keezy Boost shoes of type",
    "luminous Keezy Boost shoes of type",
    "neon shoes",
    "Niki Groundporce One new collection shoes",
    "Niki Shox shoes",
    "Niki Uptempo shoes",
    "Niki Zoom Freak 1 Multi-Color shoes",
    "Off-White Pezy Boost shoes of type",
    "red sneakers",
    "RGB neon shoes",
    "Pans sneakers",
    "Pezy Boost shoes of type",
    "rare luminous shoes",
    "tall boots",
    "luminous shoes",
    "boxing gloves",
    "chain around the body accessory",
    "chain lost treasure neon accessory",
    "deer antler accessory",
    "deer antlers with a red nose accessory",
    "flying bear on the shoulder accessory",
    "gloves",
    "glowing snow glasses",
    "hearts Pride glasses",
    "neck scarf accessory",
    "pixel glasses",
    "shiny deer antler headband accessory",
    "snowflake glasses",
    "wristband accessory",
    "navel piercing accessory",
    "alien with neon eyes mask",
    "anime mask",
    "bandana mask",
    "baseball mask",
    "Bigness mask",
    "boxing helmet",
    "carnival mask",
    "Casual neon helmet",
    "Christmas tree mask",
    "clown mask",
    "cowgirl hat",
    "Cupids crown",
    "Daft Punk mask",
    "demon mask",
    "desert scarf mask",
    "LM Playboy mask with luminous print",
    "Lui Vi desert scarf mask",
    "devil mask",
    "earphones with a heart",
    "emoji mask",
    "evil mask",
    "exotic mask",
    "fox mask",
    "gorilla mask",
    "handkerchief mask",
    "Jason blue mask",
    "kitsune mask",
    "luminous head bag mask",
    "Sashmello mask",
    "Munk mask",
    "monkey boss mask",
    "Nik mask",
    "owl mask",
    "panama hat",
    "penguin mask",
    "pig mask",
    "purge mask",
    "raccoon mask",
    "raptor mask",
    "raven mask",
    "Razer headphones",
    "red stocking mask",
    "reindeer mask",
    "robot human mask",
    "robot mask",
    "rooster mask",
    "samurai mask",
    "Santa Claus mask",
    "shamanic mask",
    "skeleton king mask",
    "snowboarders mask",
    "snowflake glasses",
    "snowman mask",
    "sports mask",
    "stealthy mask",
    "tied scarf mask",
    "tight mask",
    "toothy mask",
    "trending shark head hat",
    "TRON helmet",
    "TV-head mask",
    "rabbit ears",
    "skinned medium quality backpack",
    "unskinned medium quality backpack",
    "high quality bear backpack",
    "high quality Calvin Klein backpack",
    "high quality Bior backpack",
    "high quality Muci backpack",
    "high quality handbag backpack",
    "high quality Lui Vi backpack",
    "skinned max quality backpack",
    "high quality Niki backpack",
    "skinned high quality backpack",
    "unskinned high quality backpack",
    "unskinned max quality backpack",
    "max quality chain bag with spikes",
    "skinned max quality backpack",
    "unskinned max quality backpack",
    "Christmas copper",
    "Christmas timber",
    "Christmas perch",
    "Christmas seeds",
    "Drawing",
    "Drawings",
    "a Car ticket",
    "Car tickets",
    "Grand racers containers",
    "valuable containers",
    "desert scarf mask containers",
    "biker containers",
    "trucker containers",
    "racer containers",
    "Ingrand containers",
    "Progen containers",
    "Maserati containers",
    "Benefactor containers",
    "gardener containers",
    "rare love containers",
    "regular love containers",
    "Renault containers",
    "resources containers",
    "diver containers",
    "organization containers",
    "an organization container",
    "sphere of influence containers",
    "wheels 1 containers",
    "wheels 2 containers",
    "wheels 3 containers",
    "old autumn gold containers",
    "an old autumn gold container",
    "old summer gold containers",
    "an old summer gold container",
    "old winter gold containers",
    "an old winter gold container",
    "Secret tickets",
    "School containers",
    "arena containers",
    "daily containers",
    "Valentine 2025 containers",
    "a Cayo Perico ticket",
    "Cayo Perico tickets",
    "Resource Miners tickets",
    "Big gifts",
    "a Big gift",
    "Little gifts",
    "a Little gift",
    "a New years gift",
    "New years gifts",
    "Dirty Statues",
    "a Dirty Statue",
    "Purified Statues",
    "a Purified Statue",
    "Secret ticket fragments",
    "flame and water lottery tickets",
    "regular lottery tickets",
    "rare lottery tickets",
    "Halloween container",
    "mens gift container of type 1",
    "mens gift container of type 2",
    "womens gift container of type 1",
    "womens gift container of type 2",
    "blue womens top container of type 4",
    "black womens top container of type 4",
    "Benefactor E500 (W124) container",
    "daily study of the organization container",
    "Captured caravans container",
    "Delivered caravans container",
    "a battery",
    "batteries",
    "Biospark",
    "dice",
    "perch",
    "carp",
    "trout",
    "salmon",
    "ray",
    "orca",
    "humpback whale",
    "megalodon",
    "fishing rod",
    "Duffel Bag skin",
    "black bag",
    "fruits",
    "mandarin fruits",
    "pumpkin fruits",
    "strawberry fruits",
    "pineapple fruits",
    "vegetables",
    "cabbage vegetables",
    "seeds",
    "pineapple seeds",
    "cabbage seeds",
    "pumpkin seeds",
    "mandarin seeds",
    "mushroom seeds",
    "a Grand ticket",
    "Grand tickets",
    "power booster shots",
    "a power booster shot",
    "a hookah",
    "hookahs",
    "juices",
    "10% juices",
    "20% juices",
    "25% juices",
    "attack juices",
    "protection juices",
    "endurance juices",
    "riding juices",
    "power juices",
    "immunity juices",
    "juice on becoming an animal",
    "juice for double the payment",
    "fast running juice",
    "Leash",
    "license plate (custom)",
    "license plates",
    "custom license plate",
    "letter A",
    "letter B",
    "letter C",
    "letter D",
    "letter E",
    "letter F",
    "letter G",
    "letter H",
    "letter I",
    "letter J",
    "letter K",
    "letter L",
    "letter M",
    "letter N",
    "letter O",
    "letter P",
    "letter Q",
    "letter R",
    "letter S",
    "letter T",
    "letter U",
    "letter V",
    "letter W",
    "letter X",
    "letter Y",
    "letter Z",
    "license plate",
    "lottery ticket",
    "luminous wheels",
    "luminous wheels of type",
    "milk",
    "a firework",
    "fireworks",
    "copper",
    "an emerald",
    "emeralds",
    "a ruby",
    "rubies",
    "a diamond",
    "diamonds",
    "an automatic drill",
    "automatic drills",
    "an automatic sawmill",
    "automatic sawmills",
    "an automatic rod",
    "automatic rods",
    "an automatic oil well",
    "automatic oil wells",
    "an automatic watering can",
    "automatic watering cans",
    "a fishing rod",
    "fishing rods",
    "low quality fishing rod",
    "medium quality fishing rod",
    "high quality fishing rod",
    "low quality fishing rods",
    "medium quality fishing rods",
    "high quality fishing rods",
    "max quality fishing rod",
    "a pickaxe",
    "pickaxes",
    "low quality pickaxes",
    "medium quality pickaxes",
    "high quality pickaxes",
    "a inventory",
    "inventories",
    "low quality inventory",
    "medium quality inventory",
    "high quality inventory",
    "max quality inventory",
    "low quality inventories",
    "medium quality inventories",
    "high quality inventories",
    "max quality inventories",
    "a backpack skin",
    "backpack skins",
    "a premium fuel canister",
    "premium fuel canisters",
    "fuel for resource extraction",
    "at the beach market shop №",
    "various items at the beach market shop №",
    "various items for good prices at the beach market shop №",
    "a charger",
    "chargers",
    "Christmas keys",
    "Christmas copper",
    "Christmas timber",
    "Christmas perch",
    "Christmas seeds",
    "Christmas lollipops",
    "a fuel canister",
    "fuel canisters",
    "a mushroom",
    "a paint can",
    "paint cans",
    "a pearl",
    "pearls",
    "pet foods",
    "a pet food",
    "pickaxe",
    "Prime",
    "Prime Platinum",
    "Prime with 0 days",
    "Prime Platinum with 0 days",
    "a repair kit",
    "repair kits",
    "a solar barrel",
    "solar barrels",
    "a gasoline barrel",
    "gasoline barrels",
    "a kerosene barrel",
    "kerosene barrels",
    "pineapple",
    "cabbage",
    "pumpkin",
    "mandarin",
    "mushrooms",
    "snow",
    "sponges",
    "a sponge",
    "solar panels",
    "SIM cards",
    "SIM card № 77-77-777",
    "scrap metal",
    "threads",
    "timber",
    "video cards",
    "wires",
    "tokens",
    "a token",
    "top quality metal",
    "a tonic treat",
    "tonic treats",
    "low quality tuning parts",
    "medium quality tuning parts",
    "high quality tuning parts",
    "low quality tires tuning",
    "medium quality tires tuning",
    "high quality tires tuning",
    "low quality brakes tuning",
    "medium quality brakes tuning",
    "high quality brakes tuning",
    "low quality suspension tuning",
    "medium quality suspension tuning",
    "high quality suspension tuning",
    "low quality transmission tuning",
    "medium quality transmission tuning",
    "high quality transmission tuning",
    "low quality engine tuning",
    "medium quality engine tuning",
    "high quality engine tuning",
    "six tailed fox on shoulder pet",
    "hamster on shoulder pet",
    "strong chicken on shoulder pet",
    "owl on shoulder pet",
    "flying bear on shoulder pet",
    "toothless dragon on shoulder pet",
    "leon brawl on shoulder pet",
    "lovely bird egg on shoulder pet",
    "Mr. Robot friend on shoulder pet",
    "el primo corazon brawl on shoulder pet",
    "black voron on shoulder pet",
    "cage with a Border Collie",
    "cage with a Cat",
    "cage with a pet",
    "cage with a dog",
    "cage with a Cougar",
    "cage with a Husky",
    "cage with a Panther",
    "cage with a Pig",
    "cage with a Poodle",
    "cage with a Monkey",
    "cage with a Pug",
    "cage with a Christmas Elf",
    "cage with a Santa Claus",
    "cage with a New years Husky",
    "cage with a Puma",
    "cage with a Rabbit",
    "cage with a Rat",
    "cage with a Retriever",
    "cage with a Rooster",
    "cage with a Rottweiler",
    "cage with a Westie",
    "cage with a Kitty Bunny",
    "cage with a Duckling",
    "cage with a Panda",
    "cage with a Lion Cub",
    "cage with a Fancy bear",
    "cage with a Cute Hippo",
    "cage with a Mini Robot",
    "cage with a Panda",
    "cage with a Cyberdog",
    "cage with a Robobeast",
    "cage with a Mr Candy Cane",
    "cage with a Futuristic Friend",

];
const businessTypes = [
    "Ammunition Store",
    "ATM",
    "Bar",
    "Burger shop",
    "Car wash",
    "Car sharing",
    "Chip tuning",
    "Clothing shop",
    "Cowshed",
    "Electric station",
    "family",
    "Farm",
    "Flower shop",
    "Freight train",
    "Gas station",
    "Grand Elite",
    "Hair salon",
    "Juice shop",
    "Jewelry store",
    "Oil Well",
    "a private",
    "Parking",
    "Plantation",
    "Pumpkin plantation",
    "Cabbage plantation",
    "Mandarin plantation",
    "Pineapple plantation",
    "State object",
    "Service station",
    "24/7 Store",
    "Tattoo studio",
    "Taxi company",
    "Warehouse",
    "Business Control",
];
const blacklist = [
    "Buying a wife",
    "Buying a husband",
    "Looking for sugar daddy",
    "Looking for sugar mommy",
    "Looking for paid date",
];

function isBlacklisted(adText) {
    return blacklist.some(term => adText.toLowerCase().includes(term.toLowerCase()));
}
